### ISSUE TITLE
Configuration files for building SparseRREF.so

### ISSUE THREAD

**Issue by vchestnov** [yzhphy/NeatIBP#1]
Hi, everyone. I'm having trouble building the [SparseRREF.so](https://github.com/yzhphy/NeatIBP/tree/main/SparseRREF) shared library on my `Ubuntu 20.04` setup as I could not find the necessary `CMakeLists.txt` or `Makefile` configuration files.

Could you please upload the `CMake` or `Make` configuration files required for building the shared library? Having these files would greatly aid in the compilation and linking process.

**Comment by RWUSTC** [comment]
Hello, Seva. Thanks for pulling this issue. 

For convenience we didn't produce a proper CMake file for that shared library, which can be included in a future update. 

If you want to build that shared library, you may find the source file SparseRREF.c in src folder and complie it with GCC, for example "gcc -I/usr/local/Wolfram/Mathematica/12.0/SystemFiles/IncludeFiles/C -I$YOUR_OWN_PATH_TO_SPASM/spasm-master/src -shared -o SparseRREF.so -fPIC SparseRREF.c ". Make sure you have the path to libspasm.so included in $LD_LIBRARY_PATH. 

If you simply want to use NeatIBP, then we suggest that you directly use the pre-built SparseRREF.so in this repository. 

Hope this can solve your problem.

**Comment by vchestnov** [comment]
Hey Hefeng, thank you for your helpful response!

In the end to successfully build that shared library I did the following:

1. change the `#include` line in [SparseRREF/src/SparseRREF.c](https://github.com/yzhphy/NeatIBP/blob/ea10bf2e8fbbd1e3f17ab502e36c3e8fc4ef0d90/SparseRREF/src/SparseRREF.c#L9) to just
    ```
    #include "spasm.h"
    ```
2. compile with
    ```
    gcc -I/usr/local/Wolfram/Mathematica/13.0/SystemFiles/Links/MathLink/DeveloperKit/Linux-x86-64/CompilerAdditions/ \
        -I/usr/local/Wolfram/Mathematica/13.0/SystemFiles/IncludeFiles/C/ \
        -I/path/to/spasm/src \
        -L/path/to/spasm/build/lib -lspasm \
        -shared -o test.so -fPIC src/SparseRREF.c
    ```
